import {StyleSheet} from 'react-native';
export default StyleSheet.create({
  Utama: {
    flex: 1,
  },
  headers: {
    width: '100%',
    height: 50,
    backgroundColor: '#388e3c',
    alignItems: 'center',
    marginBottom: 5,
  },
  Tabungan: {
    alignItems: 'center',
  },
  BoxInput: {
    width: 350,
    alignSelf: 'center',
    backgroundColor: 'white',
    padding: 5,
    margin: 15,
    elevation: 5,
    borderRadius: 10,
  },
  Input: {
    height: 50,
    width: '90%',
    backgroundColor: '#C0C0C0',
    alignSelf: 'center',
    padding: 5,
    marginVertical: 5,
    elevation: 3,
    borderRadius: 5,
  },
  tombol: {
    width: 100,
    height: 50,
    backgroundColor: '#388e3c',
    alignSelf: 'center',
    marginHorizontal: 70,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
  modal: {
    flex: 1,
    width: 250,
    height: 250,
    backgroundColor: 'white',
  },
  dataMap: {
    backgroundColor: 'white',
    alignSelf: 'center',
    margin: 5,
    padding: 5,
    borderRadius: 10,
  },
  tomKonfrim: {
    margin: 10,
    width: 100,
    height: 50,
    // backgroundColor: 'red',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
  },
  imageSampah: {
    width: 100,
    height: 100,
  },
});
